# Generated by Django 4.0.4 on 2022-05-31 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nomeCompleto', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('capacidade', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nomeCompleto', models.CharField(blank=True, max_length=200)),
                ('dtnasc', models.DateField(blank=True)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCBF', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('datahora', models.DateTimeField()),
                ('numeroRodada', models.IntegerField()),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileiro.estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nomeCompleto', models.CharField(blank=True, max_length=200)),
                ('apelido', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('estadioPrincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileiro.estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Partida_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoStat', models.CharField(choices=[('G', 'Gol'), ('A', 'Assistência'), ('D', 'Advertência (Cartão Amarelo)'), ('E', 'Expulsão (Cartão Vermelho)')], default='G', max_length=1)),
                ('minuto', models.CharField(max_length=4)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileiro.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileiro.partida')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante_partida_set', to='brasileiro.time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_partida_set', to='brasileiro.time'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brasileiro.time'),
        ),
    ]
