# Generated by Django 4.0.4 on 2022-05-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brasileiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadio',
            old_name='lugares',
            new_name='capacidade',
        ),
    ]
