# Generated by Django 4.0.4 on 2022-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brasileiro', '0002_rename_lugares_estadio_capacidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadio',
            name='apelido',
        ),
        migrations.AddField(
            model_name='estadio',
            name='nomeCompleto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='capacidade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='dtnasc',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nomeCompleto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='time',
            name='apelido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='time',
            name='nomeCompleto',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
